name: Merge master
on:
  push:
    branches:
      - main
jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout work branch
        uses: actions/checkout@v3
      - name: Build sphinx documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: Commit documentation changes
        run: |
          git clone https://github.com/DOE-police/DOEDA.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
